baseURL = "https://nkapliev.org/blog/"
languageCode = "en-us"
title = "Nick Kapliev"
disqusShortname = "nkapliev"
googleAnalytics = "UA-80901629-1"

[[menu.main]]
  name = "Home"
  weight = 1
  identifier = "home"
  url = "../"
[[menu.main]]
  name = "Blog"
  weight = 2
  identifier = "blog"
  url = "/"
[[menu.main]]
  name = "Posts"
  weight = 3
  identifier = "post"
  url = "/post/"
[[menu.main]]
  name = "About"
  weight = 4
  identifier = "about"
  url = "/about/"
[params]
  related_content_limit = 1
  author = "Nick Kapliev"
  powered_by = false
  enableEmoji = true
